#!/bin/sh

sxhkd &
picom &
~/.config/polybar/launch.sh &
dunst &
feh --bg-scale ~/.config/bspwm/wallpaper.jpg
xrdb -merge ~/.Xresources &

notify-send "System is running, Try super + return for kitty"

bspc monitor -d 1 2 3 4 5

# gaps & border
bspc config border_width 1
bspc config window_gap 10

# padding layar
bspc config top_padding    40
bspc config bottom_padding 40
bspc config left_padding   40
bspc config right_padding  40


# colors
bspc config normal_border_color   "#161821"
bspc config active_border_color   "#5F6ACD"
bspc config focused_border_color  "#7A6FE3"
bspc config presel_feedback_color "#B067C9"
bspc config urgent_border_color   "#D65D6E"

# behavior
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config presel_feedback true
